asc_paths = {
    './',...
    'RealARITH',...
    'RealARITH/model',...
    'ComplexARITH',...
    'ComplexARITH/model',...
    'VHDLTools',...
    'VHDLTools/model',...
    };

for k=1:length(asc_paths)
    addpath(sprintf('%s/%s',pwd,asc_paths{k}));
end

clear asc_paths k
